baseURL: https://danking555.github.io/
languageCode: en-us
title: Area51
theme: "PaperMod"
enableRobotsTXT: true

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
    env: production
    description: "my research blog"
    DateFormat: "January 2, 2006"
    author: "Daniel Davidov"
    defaultTheme: dark
    disableThemeToggle: false
    favicon: "images/area51.avif"
    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowWordCount: true
    ShowRssButtonInSectionTermList: true
    ShowFullTextinRSS: true
    ShowAllPagesInArchive: true
    UseHugoToc: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false
    comments: true
    utterances:
      repo: "danking555/danking555.github.io"
      issueTerm: "pathname"
      label: "Comment"
      theme: "github-dark"


    # home-info mode
    homeInfoParams:
        Title: "Research And Development From Area 51"
        Content: "A place for all my niche research"
    socialIcons:
        - name: "Github"
          url: "https://github.com/Danking555"
        - name: "Linkedin"
          url: "https://www.linkedin.com/in/danieldavidov/"

menu:
  main:
    - identifier: posts
      name: Posts
      url: posts/

outputs:
  home:
    - HTML
    - RSS
    - JSON
